package io.github.aaronateataco.petsandpals.enums;

import net.minecraft.network.chat.Component;

public enum PetList {
    allay,
    parched,
    sulfur_cube,
    armadillo,
    axolotl,
    bat,
    bee,
    blaze,
    breeze,
    camel,
    cat,
    cave_spider,
    chicken,
    cod,
    copper_golem,
    cow,
    creaking,
    creeper,
    dolphin,
    donkey,
    drowned,
    elder_guardian,
    bogged,

    ender_dragon,
    enderman,
    endermite,
    evoker,
    fox,
    frog,
    ghast,
    goat,
    guardian,
    happy_ghast,
    hoglin,
    horse,
    husk,
    iron_golem,
    llama,
    magma_cube,
    mooshroom,
    nautilus,
    panda,
    parrot,
    phantom,
    pig,
    piglin,
    pillager,
    polar_bear,
    pufferfish,
    rabbit,
    ravager,
    salmon,
    sheep,
    shulker,
    silverfish,
    skeleton,
    slime,
    sniffer,
    snow_golem,
    spider,
    squid,
    strider,
    stray,
    wither_skeleton,
    tadpole,
    turtle,
    vex,
    villager,
    vindicator,
    wandering_trader,
    warden,
    witch,
    wither,
    wolf,
    zombie,
    zombie_villager;

    public Component getDisplayName() {
        return Component.literal(String.valueOf(this).replace("_", " "));
    }
}
